name: PR Comments

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Add PR comment
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo, number } = context.issue;
          
          // 기존 댓글 확인
          const comments = await github.rest.issues.listComments({
            owner,
            repo,
            issue_number: number,
          });
          
          const botComment = comments.data.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('🤖 자동 PR 검토')
          );
          
          const commentBody = `
          ## 🤖 자동 PR 검토
          
          안녕하세요! PR이 생성되었습니다. 다음 사항들을 확인해주세요:
          
          ### ✅ 체크리스트
          - [ ] 코드가 정상적으로 동작하는지 테스트했나요?
          - [ ] 새로운 기능에 대한 테스트 코드를 작성했나요?
          - [ ] 문서가 업데이트되었나요?
          - [ ] Breaking changes가 있다면 마이그레이션 가이드를 작성했나요?
          
          ### 📋 리뷰 가이드라인
          - 코드 스타일과 컨벤션을 따르고 있는지 확인
          - 성능과 보안 측면에서 문제가 없는지 검토
          - 테스트 커버리지가 충분한지 확인
          
          좋은 코드 리뷰 부탁드립니다! 🚀
          `;
          
          if (botComment) {
            // 기존 댓글 업데이트
            await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id: botComment.id,
              body: commentBody
            });
          } else {
            // 새 댓글 생성
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: commentBody
            });
          } 